[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "curl -sS https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
  "python3 get-pip.py",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r dealflow_assistant/requirements.txt"
]

[phases.start]
cmd = "uvicorn dealflow_assistant.main:app --host 0.0.0.0 --port $PORT"