[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install -r dealflow_assistant/requirements.txt"]

[phases.start]
cmd = "uvicorn dealflow_assistant.main:app --host 0.0.0.0 --port $PORT"